In [388]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [389]:
df1=pd.read_csv("Bengaluru.csv")
df1.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00

In [390]:
df1.shape

(13320, 9)

In [391]:
df2=df1.drop(['area_type','society','balcony','availability'],axis=1)
df2.head()

                   location       size total_sqft  bath   price
0  Electronic City Phase II      2 BHK       1056   2.0   39.07
1          Chikka Tirupathi  4 Bedroom       2600   5.0  120.00
2               Uttarahalli      3 BHK       1440   2.0   62.00
3        Lingadheeranahalli      3 BHK       1521   3.0   95.00
4                  Kothanur      2 BHK       1200   2.0   51.00

In [392]:
df2.isnull().sum()

location       1
size          16
total_sqft     0
bath          73
price          0
dtype: int64

In [393]:
df3=df2.dropna()
df3.isnull().sum()

location      0
size          0
total_sqft    0
bath          0
price         0
dtype: int64

In [394]:
df3['size'].unique()

array(['2 BHK', '4 Bedroom', '3 BHK', '4 BHK', '6 Bedroom', '3 Bedroom',
       '1 BHK', '1 RK', '1 Bedroom', '8 Bedroom', '2 Bedroom',
       '7 Bedroom', '5 BHK', '7 BHK', '6 BHK', '5 Bedroom', '11 BHK',
       '9 BHK', '9 Bedroom', '27 BHK', '10 Bedroom', '11 Bedroom',
       '10 BHK', '19 BHK', '16 BHK', '43 Bedroom', '14 BHK', '8 BHK',
       '12 Bedroom', '13 BHK', '18 Bedroom'], dtype=object)

In [395]:
df3['size']=df3['size'].apply(lambda x: int(x.split(' ')[0]))
df3.head()

C:\Users\AYISHA\AppData\Local\Temp\ipykernel_8368\527959381.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3['size']=df3['size'].apply(lambda x: int(x.split(' ')[0]))

                   location  size total_sqft  bath   price
0  Electronic City Phase II     2       1056   2.0   39.07
1          Chikka Tirupathi     4       2600   5.0  120.00
2               Uttarahalli     3       1440   2.0   62.00
3        Lingadheeranahalli     3       1521   3.0   95.00
4                  Kothanur     2       1200   2.0   51.00

In [396]:
df3['total_sqft'].unique()

array(['1056', '2600', '1440', ..., '1133 - 1384', '774', '4689'],
      dtype=object)

In [397]:
def is_float(x):
    try:
        float(x)
    except:
        return False
    return True
df3[~df3['total_sqft'].apply(is_float)].head(10)

               location  size      total_sqft  bath    price
30            Yelahanka     4     2100 - 2850   4.0  186.000
122              Hebbal     4     3067 - 8156   4.0  477.000
137  8th Phase JP Nagar     2     1042 - 1105   2.0   54.005
165            Sarjapur     2     1145 - 1340   2.0   43.490
188            KR Puram     2     1015 - 1540   2.0   56.800
410             Kengeri     1  34.46Sq. Meter   1.0   18.500
549         Hennur Road     2     1195 - 1440   2.0   63.770
648             Arekere     9       4125Perch   9.0  265.000
661           Yelahanka     2     1120 - 1145   2.0   48.130
672        Bettahalsoor     4     3090 - 5002   4.0  445.000

In [398]:
def convert(x):
    tokens=x.split('-')
    if len(tokens)==2:
        return ((float(tokens[0])+float(tokens[1]))/2)
    try:
        return float(x)
    except:
        return None
df4=df3.copy()        
df4['total_sqft']=df4['total_sqft'].apply(convert)
df4.head()

                   location  size  total_sqft  bath   price
0  Electronic City Phase II     2      1056.0   2.0   39.07
1          Chikka Tirupathi     4      2600.0   5.0  120.00
2               Uttarahalli     3      1440.0   2.0   62.00
3        Lingadheeranahalli     3      1521.0   3.0   95.00
4                  Kothanur     2      1200.0   2.0   51.00

In [399]:
df4.loc[30]

location      Yelahanka
size                  4
total_sqft       2475.0
bath                4.0
price             186.0
Name: 30, dtype: object

In [400]:
df5=df4.copy()
df5['price_per_sqft']=df5['price']*100000/df5['total_sqft']
df5.head()

                   location  size  total_sqft  bath   price  price_per_sqft
0  Electronic City Phase II     2      1056.0   2.0   39.07     3699.810606
1          Chikka Tirupathi     4      2600.0   5.0  120.00     4615.384615
2               Uttarahalli     3      1440.0   2.0   62.00     4305.555556
3        Lingadheeranahalli     3      1521.0   3.0   95.00     6245.890861
4                  Kothanur     2      1200.0   2.0   51.00     4250.000000

In [401]:
df5.location = df5.location.apply(lambda x: x.strip())
location_stats = df5['location'].value_counts(ascending=False)
location_stats

location
Whitefield                        535
Sarjapur  Road                    392
Electronic City                   304
Kanakpura Road                    266
Thanisandra                       236
                                 ...
Vasantapura main road               1
Bapuji Layout                       1
1st Stage Radha Krishna Layout      1
BEML Layout 5th stage               1
Abshot Layout                       1
Name: count, Length: 1293, dtype: int64

In [402]:
len(location_stats[location_stats>10])

241

In [403]:
len(df5.location.unique())

1293

In [404]:
location_stats_less_than_10 = location_stats[location_stats<=10]
location_stats_less_than_10

location
Naganathapura                     10
Sadashiva Nagar                   10
Nagappa Reddy Layout              10
BTM 1st Stage                     10
Sector 1 HSR Layout               10
                                  ..
Vasantapura main road              1
Bapuji Layout                      1
1st Stage Radha Krishna Layout     1
BEML Layout 5th stage              1
Abshot Layout                      1
Name: count, Length: 1052, dtype: int64

In [405]:
df5.location = df5.location.apply(lambda x: 'other' if x in location_stats_less_than_10  else x)
len(df5.location.unique())

242

In [406]:
df5.head()

                   location  size  total_sqft  bath   price  price_per_sqft
0  Electronic City Phase II     2      1056.0   2.0   39.07     3699.810606
1          Chikka Tirupathi     4      2600.0   5.0  120.00     4615.384615
2               Uttarahalli     3      1440.0   2.0   62.00     4305.555556
3        Lingadheeranahalli     3      1521.0   3.0   95.00     6245.890861
4                  Kothanur     2      1200.0   2.0   51.00     4250.000000

In [407]:
#removing outliers
df5.shape

(13246, 6)

In [408]:
df6 = df5[df5['total_sqft'] / df5['size'] >= 300]
df6.shape

(12456, 6)

In [409]:
#Because real estate prices vary drastically by location, filter out price_per_sqft values beyond 1 standard deviation ($\sigma$) from the location's mean ($\mu$).
def remove_pps_outliers(df):
    df_out = pd.DataFrame()
    for key, subdf in df.groupby('location'):
        m = np.mean(subdf['price_per_sqft'])
        st = np.std(subdf['price_per_sqft'])
        # Keep points within 1 standard deviation
        reduced_df = subdf[(subdf['price_per_sqft'] > (m - st)) & (subdf['price_per_sqft'] <= (m + st))]
        df_out = pd.concat([df_out, reduced_df], ignore_index=True)
    return df_out

df7 = remove_pps_outliers(df6)
df7.shape

(10241, 6)

In [410]:
#Filter out properties where a larger BHK costs less per sq ft than a smaller BHK in the same location (e.g., a 3 BHK priced lower per sq ft than the mean of 2 BHKs in that location).
def remove_bhk_outliers(df):
    exclude_indices = np.array([])
    for location, location_df in df.groupby('location'):
        bhk_stats = {}
        for bhk, bhk_df in location_df.groupby('size'):
            bhk_stats[bhk] = {
                'mean': np.mean(bhk_df.price_per_sqft),
                'std': np.std(bhk_df.price_per_sqft),
                'count': bhk_df.shape[0]
            }
        for bhk, bhk_df in location_df.groupby('size'):
            stats = bhk_stats.get(bhk-1)
            if stats and stats['count']>5:
                exclude_indices = np.append(exclude_indices, bhk_df[bhk_df.price_per_sqft<(stats['mean'])].index.values)
    return df.drop(exclude_indices,axis='index')
df8 = remove_bhk_outliers(df7)
df8.shape

(7329, 6)

In [411]:
# Keep properties where bathrooms don't exceed bedrooms + 2
df8 = df8[df8['bath'] < df8['size'] + 2]
df8.shape

(7251, 6)

In [412]:
df8['bhk']=df8['size']
df8=df8.drop('size', axis=1)
df8.head()

              location  total_sqft  bath  price  price_per_sqft  bhk
0  1st Block Jayanagar      2850.0   4.0  428.0    15017.543860    4
1  1st Block Jayanagar      1630.0   3.0  194.0    11901.840491    3
2  1st Block Jayanagar      1875.0   2.0  235.0    12533.333333    3
3  1st Block Jayanagar      1200.0   2.0  130.0    10833.333333    3
4  1st Block Jayanagar      1235.0   2.0  148.0    11983.805668    2

In [413]:
#model training
#one hot encoding
dummies=pd.get_dummies(df8.location,dtype=int)
dummies.head()

,1st Block Jayanagar,1st Phase JP Nagar,2nd Phase Judicial Layout,2nd Stage Nagarbhavi,5th Block Hbr Layout,5th Phase JP Nagar,6th Phase JP Nagar,7th Phase JP Nagar,8th Phase JP Nagar,9th Phase JP Nagar,...,Vishveshwarya Layout,Vishwapriya Layout,Vittasandra,Whitefield,Yelachenahalli,Yelahanka,Yelahanka New Town,Yelenahalli,Yeshwanthpur,other
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [414]:
#dropping the col other to avoid dummy variable trap
dummies = dummies.drop('other', axis=1)
#concat the data to original 
df8 = pd.concat([df8, dummies], axis=1)
df8 = df8.drop('location', axis=1)
df8.head()

,total_sqft,bath,price,price_per_sqft,bhk,1st Block Jayanagar,1st Phase JP Nagar,2nd Phase Judicial Layout,2nd Stage Nagarbhavi,5th Block Hbr Layout,...,Vijayanagar,Vishveshwarya Layout,Vishwapriya Layout,Vittasandra,Whitefield,Yelachenahalli,Yelahanka,Yelahanka New Town,Yelenahalli,Yeshwanthpur
0,2850.0,4.0,428.0,15017.543860,4,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1630.0,3.0,194.0,11901.840491,3,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1875.0,2.0,235.0,12533.333333,3,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1200.0,2.0,130.0,10833.333333,3,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1235.0,2.0,148.0,11983.805668,2,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [417]:
x=df8.drop(['price','price_per_sqft'],axis=1)
x

,total_sqft,bath,bhk,1st Block Jayanagar,1st Phase JP Nagar,2nd Phase Judicial Layout,2nd Stage Nagarbhavi,5th Block Hbr Layout,5th Phase JP Nagar,6th Phase JP Nagar,...,Vijayanagar,Vishveshwarya Layout,Vishwapriya Layout,Vittasandra,Whitefield,Yelachenahalli,Yelahanka,Yelahanka New Town,Yelenahalli,Yeshwanthpur
0,2850.0,4.0,4,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1630.0,3.0,3,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1875.0,2.0,3,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1200.0,2.0,3,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1235.0,2.0,2,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10232,1200.0,2.0,2,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10233,1800.0,1.0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10236,1353.0,2.0,2,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10237,812.0,1.0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10240,3600.0,5.0,4,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [418]:
y=df8.price
y

0        428.0
1        194.0
2        235.0
3        130.0
4        148.0
         ...
10232     70.0
10233    200.0
10236    110.0
10237     26.0
10240    400.0
Name: price, Length: 7251, dtype: float64

In [419]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=10)

In [421]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x_train, y_train)
score = model.score(x_test, y_test)
score

0.8452277697874391

In [422]:
#CROSS VALIDATION 
#Instead of splitting your data into a single train and test set (e.g., $80/20$), cross-validation splits the data multiple times, trains the model on different subsets, and averages the performance scores.
from sklearn.model_selection import ShuffleSplit, cross_val_score

# Randomize split across 5 folds
cv = ShuffleSplit(n_splits=5, test_size=0.2, random_state=0)
cv_scores = cross_val_score(LinearRegression(), x, y, cv=cv)

print("5-Fold Scores:", cv_scores)
print(f"Mean Score: {cv_scores.mean():.4f}")

5-Fold Scores: [0.82430186 0.77166234 0.85089567 0.80837764 0.83653286]
Mean Score: 0.8184

In [426]:
#python fn to link the model and user input
def predict_price(location, sqft, bath, bhk):
    loc_index = np.where(x.columns == location)[0][0] if location in x.columns else -1
    x_input = np.zeros(len(x.columns))
    x_input[0] = sqft
    x_input[1] = bath
    x_input[2] = bhk
    
    if loc_index >= 0:
        x_input[loc_index] = 1
    x_df = pd.DataFrame([x_input], columns=x.columns)
    
    return model.predict(x_df)[0]

In [427]:
predict_price('1st Phase JP Nagar',1000, 2, 2)

83.49904677211359

In [429]:
import pickle
import json
with open('bangalore_home_prices_model.pickle', 'wb') as f:
    pickle.dump(model, f)

columns = {
    'data_columns': [col.lower() for col in x.columns]
}
with open("columns.json", "w") as f:
    f.write(json.dumps(columns))